"""Add gemini_response to supportrequest

Revision ID: dcab7ec59fdd
Revises: 
Create Date: 2025-05-14 14:23:03.398626

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcab7ec59fdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ngoservice')
    op.drop_table('service')
    op.drop_table('ngotype')
    op.add_column('supportrequest', sa.Column('gemini_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supportrequest', 'gemini_response')
    op.create_table('ngotype',
    sa.Column('ngo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('Human_Rights_NGOs', 'Environmental_NGOs', 'Social_Welfare_NGOs', 'Development_NGOs', 'Relief_and_Recovery_NGOs', 'Advocacy_NGO', name='ngocategory'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['user.id'], name='ngotype_ngo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ngotype_pkey')
    )
    op.create_table('service',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='service_pkey')
    )
    op.create_table('ngoservice',
    sa.Column('ngo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ngoservice_pkey')
    )
    # ### end Alembic commands ###
